apiVersion: v1
entries:
  trident-installer:
  - apiVersion: v1
    appVersion: 0.0.2
    created: "2020-11-30T13:49:38.265722-07:00"
    description: Operator to install NetApp/Trident
    digest: fb2f50d8a8503852fb6a27f8c570305533d2a4b09390fcbd52a1b5605b7dc024
    icon: file://logo.png
    keywords:
    - trident
    - storage
    - block
    - iscsi
    kubeVersion: '>= 1.11.0 <= 1.19'
    name: trident-installer
    type: application
    urls:
    - trident-installer-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-11-30T13:49:38.264997-07:00"
    description: Operator to install NetApp/Trident
    digest: 9f63fb4e8c8531c425450c3f73d80536a2cdf021c31a360323db4fb51eb88fda
    icon: file://logo.png
    name: trident-installer
    type: application
    urls:
    - trident-installer-0.1.3.tgz
    version: 0.1.3
generated: "2020-11-30T13:49:38.263278-07:00"
